services:
#  app:
#    image: 'pm-sample-exec:latest'
#    networks:
#      - java-2023

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=digital
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

    restart: always
    networks:
      - java-2023

networks:
  java-2023: